import { DistributionChainEntities } from '@/types/types'

const MAXIMUM_PREVIOUS_DATA_LOOKUP_ALLOWED_IN_MONTHS = 3
const TABLE_DATE_TIME_FORMAT = 'yyyy-MMM-dd | hh:mm:ss a'

const DISTRIBUTION_ENTITY_TYPE_TO_LEVEL_MAP: Record<DistributionChainEntities, number> = {
  ADMIN: 1,
  DISTRIBUTOR: 2,
  WHOLESELLER: 3,
  RETAILER: 4
}

export { MAXIMUM_PREVIOUS_DATA_LOOKUP_ALLOWED_IN_MONTHS, TABLE_DATE_TIME_FORMAT, DISTRIBUTION_ENTITY_TYPE_TO_LEVEL_MAP }
